sources:
  - name: "Рейтер: Мир"
    name_uz: "Рейтер: Дунё"
    url: "https://www.reuters.com/world/rss"
    lang: en

  - name: "Би-би-си: Мир"
    name_uz: "Би-би-си: Дунё"
    url: "http://feeds.bbci.co.uk/news/world/rss.xml"
    lang: en

  - name: "Ассошиэйтед Пресс: Мир"
    name_uz: "Ассошиэйтед Пресс: Дунё"
    url: "https://apnews.com/hub/apf-worldnews?output=rss"
    lang: en

  - name: "The Guardian: World"
    name_uz: "The Guardian: Дунё"
    url: "https://www.theguardian.com/world/rss"
    lang: en

  - name: "Al Jazeera English"
    name_uz: "Al Jazeera"
    url: "https://www.aljazeera.com/xml/rss/all.xml"
    lang: en

  - name: "CNN: World"
    name_uz: "CNN: Дунё"
    url: "http://rss.cnn.com/rss/edition_world.rss"
    lang: en

  - name: "Euronews: World"
    name_uz: "Euronews: Дунё"
    url: "https://www.euronews.com/rss?level=theme&name=news"
    lang: en

  - name: "The Economist: Latest"
    name_uz: "The Economist"
    url: "https://www.economist.com/latest/rss.xml"
    lang: en